module.exports = {
  variables: [
    'Flow Rate ',
    'Flow Rate',
    'Energy Flow Rate',
    'Energy Flow Rate',
    'Velocity ',
    'Velocity',
    'Fluid sound ',
    'speed',
    'Fluid sound speed',
    'Positive accumulator ',
    'Positive accumulator',
    'Positive decimal fraction ',
    'Positive decimal fraction',
    'Negative accumulator',
    'Negative accumulator',
    'Negative decimal fraction',
    'Negative decimal fraction',
    'Positive energy accumulator',
    'Positive energy accumulator',
    'Positive energy decimal fraction',
    'Positive energy decimal fraction',
    'Negative energy accumulator',
    'Negative energy accumulator',
    'Negative energy decimal fraction',
    'Negative energy decimal fraction',
    'Net accumulator',
    'Net accumulator',
    'Net decimal fraction',
    'Net decimal fraction',
    'Net energy accumulator',
    'Net energy accumulator',
    'Net energy decimal fraction',
    'Net energy decimal fraction',
    'Temperature #1/inlet',
    'Temperature #1/inlet',
    'Temperature #2/outlet',
    'Temperature #2/outlet',
    'Analog input AI3]',
    'Analog input AI3',
    'Analog input AI4',
    'Analog input AI4',
    'Analog input AI5',
    'analog input AI5',
    'Current input at AI3',
    'Current input at AI3',
    'Current input at AI3',
    'Current input at AI3',
    'Current input at AI3',
    'Current input at AI3',
    'System password',
    'System password',
    'Password for hardware',
    'Calendar (date and time)',
    'Calendar (date and time)',
    'Calendar (date and time)',
    'Day+Hour for Auto-Save',
    'Key to input',
    'Go to Window #',
    'LCD Back-lit lights for number of Seconds',
    'Times for the beeper',
    'Pulses left for OCT',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'Error Code',
    'T100 resistance of inlet',
    'PT100 resistance of inlet',
    'PT100 resistance of outlet',
    'PT100 resistance of outlet',
    'Total travel time',
    'Total travel time',
    'Delta travel time',
    'Delta travel time',
    'Upstream travel time',
    'Upstream travel time',
    'Downstream travel time',
    'Downstream travel time',
    'Output current',
    'Output current',
    'Working step and Signal Quality',
    'Upstream strength ',
    'Downstream strength',
    'Language used in user interface ',
    'Upstream strength',
    'Downstream strength',
    'Language used in user interface ',
    'Upstream strength ',
    'Downstream strength',
    'Language used in user interface ',
    'The rate of the measured by travel time',
    'The rate of the measured by travel time',
    'Reynolds number ',
    'Reynolds number ',
    'Pipe Reynolds factor',
    'Pipe Reynolds factor ',
    'Working Timer ',
    'Working Timer',
  ],
}
